"""
FacesetProcessor Analyzer localization strings
人脸集分析器多语言字符串
"""
import locale

# Detect system language
def _get_system_language():
    try:
        sys_locale = locale.getdefaultlocale()[0]
        if sys_locale:
            lang = sys_locale[0:2].lower()
            if lang in ['zh', 'en']:
                return lang
    except:
        pass
    return 'en'

CURRENT_LANGUAGE = _get_system_language()

# English strings
STRINGS_EN = {
    'ANALYZER_DESCRIPTION': 'DeepFaceLab Torch - Faceset Metadata Analyzer',
    'ANALYZER_ARG_INPUT': 'Input path (faceset directory)',
    'ANALYZER_ARG_FORCE': 'Force re-analyze all images (overwrite existing data)',
    'ANALYZER_ARG_REPORT': 'Generate analysis report to file',
    'ANALYZER_ARG_MERGE': 'Merge another dataset into this one (source path)',
    'ANALYZER_ARG_FEATURES': 'Select features to analyze (comma-separated): phash, histogram, hue, pose, embedding, all (default: all)',
    'ANALYZER_ARG_WRITE_BACK': 'Write metadata back to JPG files APP15 chunk (DFL compatible mode)',
    'ANALYZER_ARG_WORKERS': 'Number of worker processes (default: CPU cores)',
    
    'ANALYZER_METADATA_LOADED': '✓ Loaded {} metadata entries',
    'ANALYZER_METADATA_LOAD_ERROR': '✗ Failed to load metadata: {}',
    'ANALYZER_NO_METADATA': 'No existing metadata found, will create new',
    'ANALYZER_FOUND_IMAGES': 'Found {} image files',
    
    'ANALYZER_VERIFYING_INTEGRITY': '\nVerifying database integrity...',
    'ANALYZER_INTEGRITY_RESULT': 'Metadata entries: {}, Actual files: {}, Missing in actual: {}, Missing in metadata: {}',
    'ANALYZER_WARNING_MISSING_FILES': '⚠ Warning: {} files exist in metadata but not on disk',
    'ANALYZER_WARNING_NEW_FILES': '⚠ Warning: {} files exist on disk but not in metadata',
    
    'ANALYZER_PHASH_ERROR': 'Failed to calculate phash for {}: {}',
    'ANALYZER_HISTOGRAM_ERROR': 'Failed to calculate histogram: {}',
    'ANALYZER_HUE_ERROR': 'Failed to calculate hue distribution: {}',
    'ANALYZER_POSE_ERROR': 'Failed to estimate face pose: {}',
    'ANALYZER_READ_ERROR': 'Failed to read image: {}',
    
    'ANALYZER_START_BATCH_ANALYSIS': '\nStarting batch analysis of {} images...',
    'ANALYZER_ALL_ANALYZED': 'All images already analyzed. Use --force to re-analyze.',
    'ANALYZER_TO_ANALYZE': 'Images to analyze: {}',
    'ANALYZER_PROGRESS': 'Analyzing',
    'ANALYZER_ANALYZE_ERROR': 'Error analyzing {}: {}',
    'ANALYZER_BATCH_COMPLETE': '\n✓ Batch analysis complete! Analyzed: {}, Errors: {}',
    'ANALYZER_SELECTED_FEATURES': 'Selected features: {}',
    'ANALYZER_AVAILABLE_FEATURES': '\nAvailable features:',
    'ANALYZER_FEATURE_PHASH': '  - phash: Perceptual hash (for duplicate detection)',
    'ANALYZER_FEATURE_HISTOGRAM': '  - histogram: RGB and HSV histogram distribution',
    'ANALYZER_FEATURE_HUE': '  - hue: Hue distribution statistics',
    'ANALYZER_FEATURE_POSE': '  - pose: Face pose angles (requires landmarks)',
    'ANALYZER_FEATURE_EMBEDDING': '  - embedding: Face feature vector (ArcFace)',
    'ANALYZER_FEATURE_ALL': '  - all: All features',
    'ANALYZER_INVALID_FEATURE': '⚠ Invalid feature option: {}',
    'ANALYZER_FILE_NOT_FOUND': '✗ File not found: {}',
    'ANALYZER_NO_METADATA_FOR_FILE': '✗ No metadata for file: {}',
    'ANALYZER_INVALID_JPG': '✗ Invalid JPG file: {}',
    'ANALYZER_WRITE_METADATA_ERROR': '✗ Failed to write metadata {}: {}',
    'ANALYZER_START_BATCH_WRITE': '\nStarting batch write metadata to JPG files ({} images)...',
    'ANALYZER_WRITE_PROGRESS': 'Writing',
    'ANALYZER_BATCH_WRITE_COMPLETE': '\n✓ Batch write complete! Success: {}, Errors: {}',
    
    'ANALYZER_METADATA_SAVED': '✓ Metadata saved ({} entries)',
    'ANALYZER_SAVING_METADATA': 'Saving metadata to file ({} entries)...',
    'ANALYZER_SAVE_ERROR': 'Failed to save metadata: {}',
    
    'ANALYZER_GENERATING_REPORT': '\nGenerating analysis report...',
    'ANALYZER_REPORT_SAVED': '✓ Report saved to: {}',
    
    'MERGER_START_MERGE': '\nStarting dataset merge: {} → {}',
    'MERGER_SOURCE_METADATA_LOADED': '✓ Loaded source metadata: {} entries',
    'MERGER_SOURCE_FOUND_IMAGES': 'Found {} images in source dataset',
    'MERGER_BUILDING_INDEX': 'Building phash index: {} entries',
    'MERGER_PROGRESS': 'Merging',
    'MERGER_DUPLICATE_FOUND': '  Duplicate: {} ≈ {} (distance: {})',
    'MERGER_COPY_ERROR': 'Error copying {}: {}',
    'MERGER_COMPLETE': '\n✓ Merge complete!',
    'MERGER_STAT_TOTAL': 'Total source files',
    'MERGER_STAT_DUPLICATES': 'Duplicates found',
    'MERGER_STAT_COPIED': 'Files copied',
    'MERGER_STAT_RENAMED': 'Files renamed',
    'MERGER_STAT_METADATA': 'Metadata merged',
    'MERGER_STAT_ERRORS': 'Errors',
    
    'FILTER_DESCRIPTION': 'DeepFaceLab Torch - Faceset Quality Filter',
    'FILTER_ARG_INPUT': 'Input path (faceset directory)',
    'FILTER_ARG_MODE': 'Filter mode: quality (blur detection), faceid (face grouping), position (position clustering), or repeated (duplicate removal)',
    'FILTER_ARG_THRESHOLD': 'Threshold value (quality: variance threshold, faceid: similarity threshold, repeated: hash similarity)',
    'FILTER_ARG_WORKERS': 'Number of worker processes (default: CPU cores)',
    
    'FILTER_METADATA_LOADED': '✓ Loaded {} metadata entries',
    'FILTER_INSIGHTFACE_NOT_INSTALLED': '⚠ InsightFace not installed, will use landmarks fallback',
    'FILTER_INSTALL_INSTRUCTIONS': '\nTo install: pip install insightface==0.7.3\nOr use conda: conda install -c conda-forge insightface',
    'FILTER_INIT_ARCFACE_ONNX': '\nInitializing ArcFace ONNX extractor...',
    'FILTER_LOADING_ARCFACE_MODEL': 'Loading ArcFace model: {}',
    'FILTER_ARCFACE_MODEL_LOADED': '✓ ArcFace model loaded',
    'FILTER_LOADING_DET_MODEL': 'Loading detection model: {}',
    'FILTER_DET_MODEL_LOADED': '✓ Detection model loaded',
    'FILTER_DET_MODEL_NOT_FOUND': '⚠ Detection model not found, using full image',
    'FILTER_DET_ERROR': 'Detection error: {}',
    'FILTER_ARCFACE_ONNX_READY': '✓ ArcFace ONNX ready',
    'FILTER_ARCFACE_ONNX_FAILED': '✗ ArcFace ONNX failed: {}',
    'FILTER_MODELHUB_NOT_FOUND': '⚠ Model directory not found',
    'FILTER_INSIGHTFACE_FAILED': '✗ InsightFace failed: {}',
    'FILTER_INIT_INSIGHTFACE': '\nInitializing InsightFace...',
    'FILTER_INSIGHTFACE_READY': '✓ InsightFace ready',
    'FILTER_USING_LANDMARKS_FALLBACK': '⚠ Using landmarks fallback (less accurate)',
    'FILTER_SHARPNESS_ERROR': 'Failed to calculate sharpness: {}',
    'FILTER_IMAGE_READ_ERROR': 'Warning: Could not read image {}',
    'FILTER_ARCFACE_RETURNED_NONE': 'Warning: ArcFace returned None for {}',
    'FILTER_INSIGHTFACE_NO_FACE': 'Warning: No face detected in {} by InsightFace',
    'FILTER_NO_EXTRACTION_MODEL': '\nWarning: No face recognition model available!',
    'FILTER_CHECK_MODEL_PATH': 'Please check if model files exist in modelhub/onnx/ArcFace/',
    'FILTER_SUPPORTED_MODELS': 'Supported models: w600k_mbf.onnx, w600k_r50.onnx',
    'FILTER_CURRENT_MODEL_PATH': 'Current search path: {}',
    'FILTER_START_QUALITY_FILTER': '\nStarting quality filter (threshold: {})...',
    'FILTER_FOUND_IMAGES': 'Found {} images',
    'FILTER_PHASE1_CALCULATING': '\nPhase 1: Calculating sharpness...',
    'FILTER_USING_WORKERS': 'Using {} worker processes',
    'FILTER_PROGRESS_QUALITY': 'Filtering',
    'FILTER_NO_LANDMARKS': 'No landmarks for {}: skipping',
    'FILTER_PROCESS_ERROR': 'Error processing {}: {}',
    'FILTER_PHASE2_CLASSIFYING': '\nPhase 2: Classifying results...',
    'FILTER_PHASE3_MOVING': '\nPhase 3: Moving {} files...',
    'FILTER_PROGRESS_MOVING': 'Moving',
    'FILTER_MOVE_ERROR': 'Error moving {}: {}',
    'FILTER_QUALITY_COMPLETE': '\n✓ Quality filter complete!',
    'FILTER_STAT_HIGH': 'High quality',
    'FILTER_STAT_LOW': 'Low quality',
    
    'FILTER_EMBEDDING_ERROR': 'Failed to extract embedding for {}: {}',
    'FILTER_SIMILARITY_ERROR': 'Failed to calculate similarity: {}',
    'FILTER_START_FACEID_FILTER': '\nStarting face ID filter (threshold: {})...',
    'FILTER_NO_IMAGES_FOUND': 'No images found!',
    'FILTER_PHASE1_EXTRACTING_EMBEDDINGS': '\nPhase 1: Extracting embeddings...',
    'FILTER_PROGRESS_EXTRACTING': 'Extracting',
    'FILTER_EMBEDDINGS_EXTRACTED': '✓ Extracted {} embeddings ({} failed)',
    'FILTER_NO_EMBEDDINGS': '✗ No embeddings extracted!',
    'FILTER_PHASE2_GROUPING': '\nPhase 2: Grouping by face ID...',
    'FILTER_PROGRESS_FACEID': 'Grouping',
    'FILTER_MOVING_FILES': '\nMoving files to {} groups...',
    'FILTER_FACEID_COMPLETE': '\n✓ Face ID filter complete!',
    'FILTER_STAT_GROUPS': 'Total groups',
    'FILTER_STAT_FAILED': 'Failed extractions',
    'FILTER_STAT_TOTAL': 'Total',
    'FILTER_STAT_ERRORS': 'Errors',
    'FILTER_STAT_NOISE': 'Unclassified (noise)',
    
    'FILTER_AVAILABLE_MODELS': 'Available models',
    'FILTER_SELECT_MODEL': 'Select model to use:',
    'FILTER_RECOMMENDED': '(recommended)',
    'FILTER_ENTER_CHOICE': 'Enter choice ({}-{}, default={}): ',
    'FILTER_INVALID_CHOICE': 'Invalid choice, using default: {}',
    'FILTER_USING_DEFAULT': 'Using default model: {}',
    'FILTER_ARG_MODEL': 'Specify face recognition model (default: auto-select best)',
    'FILTER_ARG_EPS': 'DBSCAN neighborhood radius (cosine distance space), default 0.3 (similarity >= 0.7)',
    'FILTER_ARG_MIN_SAMPLES': 'DBSCAN minimum samples per cluster, default 2',
    'FILTER_USING_CACHED_EMBEDDINGS': 'Using cached embeddings from metadata',
    'FILTER_DBSCLAN_INFO': 'Using DBSCAN clustering (eps={}, min_samples={})',
    'FILTER_COMPUTING_SIMILARITY': 'Computing cosine similarity matrix...',
    'FILTER_RUNNING_DBSCLAN': 'Running DBSCAN clustering...',
    'FILTER_CLUSTERING_RESULTS': '\nClustering results:',
    'FILTER_TOTAL_CLUSTERS': '  Total clusters: {}',
    'FILTER_NOISE_POINTS': '  Noise points (unclassified): {}',
    'FILTER_MOVING_NOISE': '  Moving {} unclassified images to \'faceid_noise/\'',
    'FILTER_SAVING_EMBEDDINGS': '\nSaving new embeddings to metadata...',
    'FILTER_EMBEDDINGS_SAVED': '✓ Saved {} new embeddings to metadata.json',
    'FILTER_SAVE_METADATA_WARNING': '⚠ Warning: Could not save metadata: {}',
    'FILTER_EMBEDDINGS_ALREADY_SAVED': '✓ All embeddings were already in metadata, no update needed',
    'FILTER_START_POSITION_FILTER': '\nStarting position-based filter (eps: {} pixels)...',
    'FILTER_PHASE1_EXTRACTING_POSITIONS': '\nPhase 1: Extracting face positions...',
    'FILTER_POSITIONS_EXTRACTED': '✓ Extracted {} positions ({} failed)',
    'FILTER_NO_POSITIONS': '✗ No position data extracted!',
    'FILTER_PHASE2_CLUSTERING_POSITIONS': '\nPhase 2: Clustering by position...',
    'FILTER_RUNNING_DBSCLAN_POSITION': 'Running DBSCAN clustering (eps={}, min_samples={})...',
    'FILTER_POSITION_COMPLETE': '\n✓ Position filter complete!',
    
    'FILTER_START_REPEATED_FILTER': '\nStarting duplicate removal filter (threshold: {}, method: {})...',
    'FILTER_HASH_METHOD_PHASH': 'Using perceptual hash (phash)',
    'FILTER_HASH_METHOD_AHASH': 'Using average hash (ahash)',
    'FILTER_HASH_METHOD_DHASH': 'Using difference hash (dhash)',
    'FILTER_PHASE1_CALCULATING_HASHES': '\nPhase 1: Calculating image hashes...',
    'FILTER_PROGRESS_HASHING': 'Hashing',
    'FILTER_HASH_ERROR': 'Failed to calculate hash for {}: {}',
    'FILTER_PHASE2_SEQUENTIAL_SCAN': '\nPhase 2: Sequential scan for duplicates...',
    'FILTER_PROGRESS_LOADING_HASHES': 'Loading hashes',
    'FILTER_PHASE3_MARKING_DUPLICATES': '\nPhase 3: Marking duplicates...',
    'FILTER_PROGRESS_SCANNING': 'Scanning',
    'FILTER_FOUND_DUPLICATES': 'Found {} duplicates',
    'FILTER_PHASE3_MOVING_DUPLICATES': '\nPhase 4: Moving {} duplicate files to repeated/...',
    'FILTER_REPEATED_COMPLETE': '\n✓ Duplicate removal complete!',
    'FILTER_STAT_MOVED': 'Moved duplicates',
    'FILTER_STAT_REMAINING': 'Remaining images',
    'FILTER_STAT_REDUCTION': 'Reduction percentage',
    
    'SORTER_DESCRIPTION': 'DeepFaceLab Torch - Faceset Sorter',
    'SORTER_ARG_INPUT': 'Input path (faceset directory)',
    'SORTER_ARG_METHOD': 'Sort method',
    'SORTER_ARG_RENAME': 'Rename sorted files',
    'SORTER_ARG_PREFIX': 'Rename prefix',
    'SORTER_ARG_WORKERS': 'Number of worker processes (default: CPU cores)',
    'SORTER_ARG_POSE_TYPE': 'Pose type (only for face_pose sort)',
    'SORTER_ARG_MOTION_BLUR': 'Use motion blur detection',
    
    'SORTER_METADATA_LOADED': '✓ Loaded {} metadata entries',
    'SORTER_METADATA_LOAD_ERROR': '✗ Failed to load metadata: {}',
    'SORTER_NO_METADATA': 'No existing metadata found',
    'SORTER_FOUND_IMAGES': 'Found {} image files',
    
    'SORTER_SORTING_BY': '\nSorting by {}...',
    'SORTER_CALCULATING_PHASH': 'Calculating phash ({} images)...',
    'SORTER_CALCULATING_HIST': 'Calculating histogram ({} images)...',
    'SORTER_CALCULATING_BLUR': 'Calculating blur ({} images)...',
    'SORTER_CALCULATING_POSE': 'Calculating face pose ({} images)...',
    'SORTER_CALCULATING_RESOLUTION': 'Calculating resolution ({} images)...',
    'SORTER_CALCULATING_COLOR': 'Calculating color ({} images)...',
    
    'SORTER_SORTING_SIMILARITY': 'Sorting by similarity...',
    'SORTER_SORTING_BY_HIST': 'Sorting by histogram...',
    'SORTER_SORTING_BY_BLUR': 'Sorting by blur (high to low)...',
    'SORTER_SORTING_BY_POSE': 'Sorting by {} pose...',
    'SORTER_SORTING_BY_RESOLUTION': 'Sorting by resolution (low to high)...',
    'SORTER_SORTING_BY_COLOR': 'Sorting by color...',
    'SORTER_SORTING_BY_NAME': 'Sorting by name...',
    
    'SORTER_RENAMING_FILES': 'Renaming {} files...',
    'SORTER_RENAME_COMPLETE': '✓ Rename complete',
}

# Chinese strings
STRINGS_ZH = {
    'ANALYZER_DESCRIPTION': 'DeepFaceLab Torch - 人脸集元数据分析器',
    'ANALYZER_ARG_INPUT': '输入路径（人脸集目录）',
    'ANALYZER_ARG_FORCE': '强制重新分析所有图像（覆盖已有数据）',
    'ANALYZER_ARG_REPORT': '生成分析报告到指定文件',
    'ANALYZER_ARG_MERGE': '合并另一个数据集到当前目录（源路径）',
    'ANALYZER_ARG_FEATURES': '选择要分析的特征（可多选，用逗号分隔）: phash, histogram, hue, pose, embedding, all（默认: all）',
    'ANALYZER_ARG_WRITE_BACK': '将元数据写回 JPG 文件的 APP15 chunk（DFL 兼容模式）',
    'ANALYZER_ARG_WORKERS': '工作进程数（默认: CPU 核心数）',
    
    'ANALYZER_METADATA_LOADED': '✓ 已加载 {} 条元数据',
    'ANALYZER_METADATA_LOAD_ERROR': '✗ 加载元数据失败: {}',
    'ANALYZER_NO_METADATA': '未找到现有元数据，将创建新的',
    'ANALYZER_FOUND_IMAGES': '找到 {} 个图像文件',
    
    'ANALYZER_VERIFYING_INTEGRITY': '\n正在校验数据库完整性...',
    'ANALYZER_INTEGRITY_RESULT': '元数据条目: {}, 实际文件: {}, 元数据中有但磁盘缺失: {}, 磁盘有但元数据缺失: {}',
    'ANALYZER_WARNING_MISSING_FILES': '⚠ 警告: {} 个文件存在于元数据中但磁盘上不存在',
    'ANALYZER_WARNING_NEW_FILES': '⚠ 警告: {} 个文件存在于磁盘上但未在元数据中记录',
    
    'ANALYZER_PHASH_ERROR': '计算感知哈希失败 {}: {}',
    'ANALYZER_HISTOGRAM_ERROR': '计算直方图失败: {}',
    'ANALYZER_HUE_ERROR': '计算色相分布失败: {}',
    'ANALYZER_POSE_ERROR': '估算人脸姿态失败: {}',
    'ANALYZER_READ_ERROR': '读取图像失败: {}',
    
    'ANALYZER_START_BATCH_ANALYSIS': '\n开始批量分析 {} 张图像...',
    'ANALYZER_ALL_ANALYZED': '所有图像已分析完成。使用 --force 参数可重新分析。',
    'ANALYZER_TO_ANALYZE': '待分析图像数: {}',
    'ANALYZER_PROGRESS': '分析中',
    'ANALYZER_ANALYZE_ERROR': '分析出错 {}: {}',
    'ANALYZER_BATCH_COMPLETE': '\n✓ 批量分析完成！成功: {}, 错误: {}',
    'ANALYZER_SELECTED_FEATURES': '已选择的分析特征: {}',
    'ANALYZER_AVAILABLE_FEATURES': '\n可用分析特征:',
    'ANALYZER_FEATURE_PHASH': '  - phash: 感知哈希（用于重复检测）',
    'ANALYZER_FEATURE_HISTOGRAM': '  - histogram: RGB和HSV直方图分布',
    'ANALYZER_FEATURE_HUE': '  - hue: 色相分布统计',
    'ANALYZER_FEATURE_POSE': '  - pose: 人脸姿态角度（需要landmarks）',
    'ANALYZER_FEATURE_EMBEDDING': '  - embedding: 人脸特征向量（ArcFace）',
    'ANALYZER_FEATURE_ALL': '  - all: 全部特征',
    'ANALYZER_INVALID_FEATURE': '⚠ 无效的特征选项: {}',
    'ANALYZER_FILE_NOT_FOUND': '✗ 文件不存在: {}',
    'ANALYZER_NO_METADATA_FOR_FILE': '✗ 文件没有元数据: {}',
    'ANALYZER_INVALID_JPG': '✗ 无效的 JPG 文件: {}',
    'ANALYZER_WRITE_METADATA_ERROR': '✗ 写入元数据失败 {}: {}',
    'ANALYZER_START_BATCH_WRITE': '\n开始批量写入元数据到 JPG 文件 ({} 张)...',
    'ANALYZER_WRITE_PROGRESS': '写入中',
    'ANALYZER_BATCH_WRITE_COMPLETE': '\n✓ 批量写入完成！成功: {}, 错误: {}',
    
    'ANALYZER_METADATA_SAVED': '✓ 元数据已保存 ({} 条)',
    'ANALYZER_SAVING_METADATA': '正在保存元数据到文件 ({} 条)...',
    'ANALYZER_SAVE_ERROR': '保存元数据失败: {}',
    
    'ANALYZER_GENERATING_REPORT': '\n正在生成分析报告...',
    'ANALYZER_REPORT_SAVED': '✓ 报告已保存到: {}',
    
    'MERGER_START_MERGE': '\n开始合并数据集: {} → {}',
    'MERGER_SOURCE_METADATA_LOADED': '✓ 已加载源元数据: {} 条',
    'MERGER_SOURCE_FOUND_IMAGES': '在源数据集中找到 {} 张图像',
    'MERGER_BUILDING_INDEX': '构建 phash 索引: {} 条',
    'MERGER_PROGRESS': '合并中',
    'MERGER_DUPLICATE_FOUND': '  重复: {} ≈ {} (距离: {})',
    'MERGER_COPY_ERROR': '复制出错 {}: {}',
    'MERGER_COMPLETE': '\n✓ 合并完成！',
    'MERGER_STAT_TOTAL': '源文件总数',
    'MERGER_STAT_DUPLICATES': '发现重复',
    'MERGER_STAT_COPIED': '已复制',
    'MERGER_STAT_RENAMED': '已重命名',
    'MERGER_STAT_METADATA': '元数据合并',
    'MERGER_STAT_ERRORS': '错误',
    
    'FILTER_DESCRIPTION': 'DeepFaceLab Torch - 人脸集质量过滤器',
    'FILTER_ARG_INPUT': '输入路径（人脸集目录）',
    'FILTER_ARG_MODE': '过滤模式：quality（模糊检测）或 faceid（人脸分组）',
    'FILTER_ARG_THRESHOLD': '阈值（quality: 方差阈值, faceid: 相似度阈值）',
    'FILTER_ARG_WORKERS': '工作进程数（默认: CPU 核心数）',
    
    'FILTER_METADATA_LOADED': '✓ 已加载 {} 条元数据',
    'FILTER_INSIGHTFACE_NOT_INSTALLED': '⚠ InsightFace 未安装，将使用 landmarks 降级方案',
    'FILTER_INSTALL_INSTRUCTIONS': '\n安装方法: pip install insightface==0.7.3\n或使用 conda: conda install -c conda-forge insightface',
    'FILTER_INIT_ARCFACE_ONNX': '\n正在初始化 ArcFace ONNX 提取器...',
    'FILTER_LOADING_ARCFACE_MODEL': '加载 ArcFace 模型: {}',
    'FILTER_ARCFACE_MODEL_LOADED': '✓ ArcFace 模型已加载',
    'FILTER_LOADING_DET_MODEL': '加载检测模型: {}',
    'FILTER_DET_MODEL_LOADED': '✓ 检测模型已加载',
    'FILTER_DET_MODEL_NOT_FOUND': '⚠ 未找到检测模型，使用整张图像',
    'FILTER_DET_ERROR': '检测出错: {}',
    'FILTER_ARCFACE_ONNX_READY': '✓ ArcFace ONNX 就绪',
    'FILTER_ARCFACE_ONNX_FAILED': '✗ ArcFace ONNX 失败: {}',
    'FILTER_MODELHUB_NOT_FOUND': '⚠ 未找到模型目录',
    'FILTER_INSIGHTFACE_FAILED': '✗ InsightFace 失败: {}',
    'FILTER_INIT_INSIGHTFACE': '\n正在初始化 InsightFace...',
    'FILTER_INSIGHTFACE_READY': '✓ InsightFace 就绪',
    'FILTER_USING_LANDMARKS_FALLBACK': '⚠ 使用 landmarks 降级方案（精度较低）',
    'FILTER_SHARPNESS_ERROR': '计算清晰度失败: {}',
    'FILTER_IMAGE_READ_ERROR': '警告: 无法读取图像 {}',
    'FILTER_ARCFACE_RETURNED_NONE': '警告: ArcFace 返回 None: {}',
    'FILTER_INSIGHTFACE_NO_FACE': '警告: InsightFace 未检测到人脸: {}',
    'FILTER_NO_EXTRACTION_MODEL': '\n警告: 没有可用的人脸识别模型！',
    'FILTER_CHECK_MODEL_PATH': '请检查 modelhub/onnx/ArcFace/ 下是否有模型文件',
    'FILTER_SUPPORTED_MODELS': '支持的模型: w600k_mbf.onnx, w600k_r50.onnx',
    'FILTER_CURRENT_MODEL_PATH': '当前查找路径: {}',
    'FILTER_START_QUALITY_FILTER': '\n开始质量过滤（阈值: {}）...',
    'FILTER_FOUND_IMAGES': '找到 {} 张图像',
    'FILTER_PHASE1_CALCULATING': '\n第一阶段：计算清晰度...',
    'FILTER_USING_WORKERS': '使用 {} 个工作进程',
    'FILTER_PROGRESS_QUALITY': '过滤中',
    'FILTER_NO_LANDMARKS': '{} 缺少 landmarks，跳过',
    'FILTER_PROCESS_ERROR': '处理出错 {}: {}',
    'FILTER_PHASE2_CLASSIFYING': '\n第二阶段：分类结果...',
    'FILTER_PHASE3_MOVING': '\n第三阶段：移动 {} 个文件...',
    'FILTER_PROGRESS_MOVING': '移动中',
    'FILTER_MOVE_ERROR': '移动出错 {}: {}',
    'FILTER_QUALITY_COMPLETE': '\n✓ 质量过滤完成！',
    'FILTER_STAT_HIGH': '高质量',
    'FILTER_STAT_LOW': '低质量',
    
    'FILTER_EMBEDDING_ERROR': '提取 embedding 失败 {}: {}',
    'FILTER_SIMILARITY_ERROR': '计算相似度失败: {}',
    'FILTER_START_FACEID_FILTER': '\n开始人脸 ID 过滤（阈值: {}）...',
    'FILTER_NO_IMAGES_FOUND': '未找到图像！',
    'FILTER_PHASE1_EXTRACTING_EMBEDDINGS': '\n第一阶段：提取 embedding...',
    'FILTER_PROGRESS_EXTRACTING': '提取中',
    'FILTER_EMBEDDINGS_EXTRACTED': '✓ 已提取 {} 个 embedding（{} 个失败）',
    'FILTER_NO_EMBEDDINGS': '✗ 未提取到任何 embedding！',
    'FILTER_PHASE2_GROUPING': '\n第二阶段：按人脸 ID 分组...',
    'FILTER_PROGRESS_FACEID': '分组中',
    'FILTER_MOVING_FILES': '\n正在移动文件到 {} 个组...',
    'FILTER_FACEID_COMPLETE': '\n✓ 人脸 ID 过滤完成！',
    'FILTER_STAT_GROUPS': '总组数',
    'FILTER_STAT_FAILED': '提取失败',
    'FILTER_STAT_TOTAL': '总数',
    'FILTER_STAT_ERRORS': '错误',
    'FILTER_STAT_NOISE': '未分类（噪声）',
    
    'FILTER_AVAILABLE_MODELS': '可用模型',
    'FILTER_SELECT_MODEL': '选择要使用的模型:',
    'FILTER_RECOMMENDED': '(推荐)',
    'FILTER_ENTER_CHOICE': '输入选项 ({}-{}, 默认={}): ',
    'FILTER_INVALID_CHOICE': '无效选项，使用默认: {}',
    'FILTER_USING_DEFAULT': '使用默认模型: {}',
    'FILTER_ARG_MODEL': '指定人脸识别模型（默认：自动选择最优）',
    'FILTER_ARG_EPS': 'DBSCAN 邻域半径参数（余弦距离空间），默认0.3（对应相似度0.7）',
    'FILTER_ARG_MIN_SAMPLES': 'DBSCAN 最小样本数，默认2',
    'FILTER_USING_CACHED_EMBEDDINGS': '使用元数据中缓存的 embedding',
    'FILTER_DBSCLAN_INFO': '使用 DBSCAN 聚类算法 (eps={}, min_samples={})',
    'FILTER_COMPUTING_SIMILARITY': '计算余弦相似度矩阵...',
    'FILTER_RUNNING_DBSCLAN': '执行 DBSCAN 聚类...',
    'FILTER_CLUSTERING_RESULTS': '\n聚类结果：',
    'FILTER_TOTAL_CLUSTERS': '  总簇数: {}',
    'FILTER_NOISE_POINTS': '  噪声点（无法归类）: {}',
    'FILTER_MOVING_NOISE': '  移动 {} 张未分类图片到 \'faceid_noise/\'',
    'FILTER_SAVING_EMBEDDINGS': '\n正在保存新提取的 embedding 到元数据...',
    'FILTER_EMBEDDINGS_SAVED': '✓ 已保存 {} 个新的 embedding 到 metadata.json',
    'FILTER_SAVE_METADATA_WARNING': '⚠ 警告: 无法保存元数据: {}',
    'FILTER_EMBEDDINGS_ALREADY_SAVED': '✓ 所有 embedding 已在元数据中，无需更新',
    'FILTER_START_POSITION_FILTER': '\n开始基于位置的过滤（eps: {} 像素）...',
    'FILTER_PHASE1_EXTRACTING_POSITIONS': '\n第一阶段：提取人脸位置...',
    'FILTER_POSITIONS_EXTRACTED': '✓ 已提取 {} 个位置（{} 个失败）',
    'FILTER_NO_POSITIONS': '✗ 未提取到任何位置数据！',
    'FILTER_PHASE2_CLUSTERING_POSITIONS': '\n第二阶段：按位置聚类...',
    'FILTER_RUNNING_DBSCLAN_POSITION': '执行 DBSCAN 聚类 (eps={}, min_samples={})...',
    'FILTER_POSITION_COMPLETE': '\n✓ 位置过滤完成！',
    
    'FILTER_START_REPEATED_FILTER': '\n开始去重过滤（阈值: {}, 方法: {}）...',
    'FILTER_HASH_METHOD_PHASH': '使用感知哈希 (phash)',
    'FILTER_HASH_METHOD_AHASH': '使用平均哈希 (ahash)',
    'FILTER_HASH_METHOD_DHASH': '使用差异哈希 (dhash)',
    'FILTER_PHASE1_CALCULATING_HASHES': '\n第一阶段：计算图像哈希...',
    'FILTER_PROGRESS_HASHING': '计算哈希',
    'FILTER_HASH_ERROR': '计算哈希失败 {}: {}',
    'FILTER_PHASE2_SEQUENTIAL_SCAN': '\n第二阶段：顺序扫描重复图片...',
    'FILTER_PROGRESS_LOADING_HASHES': '加载哈希',
    'FILTER_PHASE3_MARKING_DUPLICATES': '\n第三阶段：标记重复图片...',
    'FILTER_PROGRESS_SCANNING': '扫描中',
    'FILTER_FOUND_DUPLICATES': '发现 {} 个重复',
    'FILTER_PHASE3_MOVING_DUPLICATES': '\n第四阶段：移动 {} 个重复文件到 repeated/...',
    'FILTER_REPEATED_COMPLETE': '\n✓ 去重完成！',
    'FILTER_STAT_MOVED': '已移动重复',
    'FILTER_STAT_REMAINING': '剩余图片',
    'FILTER_STAT_REDUCTION': '减少百分比',
    
    'SORTER_DESCRIPTION': 'DeepFaceLab Torch - 人脸集排序器',
    'SORTER_ARG_INPUT': '输入路径（人脸集目录）',
    'SORTER_ARG_METHOD': '排序方法',
    'SORTER_ARG_RENAME': '重命名排序后的文件',
    'SORTER_ARG_PREFIX': '重命名前缀',
    'SORTER_ARG_WORKERS': '工作进程数（默认: CPU 核心数）',
    'SORTER_ARG_POSE_TYPE': '姿态类型（仅用于face_pose排序）',
    'SORTER_ARG_MOTION_BLUR': '使用运动模糊检测',
    
    'SORTER_METADATA_LOADED': '✓ 已加载 {} 条元数据',
    'SORTER_METADATA_LOAD_ERROR': '✗ 加载元数据失败: {}',
    'SORTER_NO_METADATA': '未找到现有元数据',
    'SORTER_FOUND_IMAGES': '找到 {} 个图像文件',
    
    'SORTER_SORTING_BY': '\n按 {} 排序...',
    'SORTER_CALCULATING_PHASH': '计算感知哈希 ({} 张)...',
    'SORTER_CALCULATING_HIST': '计算直方图 ({} 张)...',
    'SORTER_CALCULATING_BLUR': '计算模糊度 ({} 张)...',
    'SORTER_CALCULATING_POSE': '计算人脸姿态 ({} 张)...',
    'SORTER_CALCULATING_RESOLUTION': '计算分辨率 ({} 张)...',
    'SORTER_CALCULATING_COLOR': '计算颜色 ({} 张)...',
    
    'SORTER_SORTING_SIMILARITY': '按相似度排序...',
    'SORTER_SORTING_BY_HIST': '按直方图排序...',
    'SORTER_SORTING_BY_BLUR': '按模糊度排序（从高到低）...',
    'SORTER_SORTING_BY_POSE': '按 {} 姿态排序...',
    'SORTER_SORTING_BY_RESOLUTION': '按分辨率排序（从低到高）...',
    'SORTER_SORTING_BY_COLOR': '按颜色排序...',
    'SORTER_SORTING_BY_NAME': '按文件名排序...',
    
    'SORTER_RENAMING_FILES': '重命名 {} 个文件...',
    'SORTER_RENAME_COMPLETE': '✓ 重命名完成',
}

# Language strings database
STRINGS_DB = {
    'en': STRINGS_EN,
    'zh': STRINGS_ZH,
}


def S(key, *args):
    """
    Get localized string
    Usage: S('KEY_NAME') or S('KEY_WITH_FORMAT', arg1, arg2)
    """
    db = STRINGS_DB.get(CURRENT_LANGUAGE, STRINGS_DB['en'])
    text = db.get(key, key)  # Fallback to key if not found
    if args:
        return text.format(*args)
    return text


def set_language(lang):
    """Set current language ('en' or 'zh')"""
    global CURRENT_LANGUAGE
    if lang in STRINGS_DB:
        CURRENT_LANGUAGE = lang
