import sys

f = r'C:\MySoftware\dfl-pytorch\DeepFaceLab-Torch-main\models\Model_AMP\Model_pytorch.py'
with open(f, 'r', encoding='utf-8') as fp:
    content = fp.read()

old = (
    '\t\t# ---- filename labels below each cell (purple-blue gradient strip) ----\n'
    '\t\ttry:\n'
    '\t\t\tfrom PIL import Image, ImageDraw, ImageFont\n'
    '\t\t\tsrc_fnames = self.last_filenames[0] if hasattr(self, \'last_filenames\') and len(self.last_filenames) > 0 else []\n'
    '\t\t\tdst_fnames = self.last_filenames[1] if hasattr(self, \'last_filenames\') and len(self.last_filenames) > 1 else []\n'
    '\n'
    '\t\t\tdef _label_strip(w, text, iter_val):\n'
    '\t\t\t\tLABEL_H = 22\n'
    '\t\t\t\tstrip = np.full((LABEL_H, w, 3), 0.03, dtype=np.float32)\n'
    '\t\t\t\tif not text:\n'
    '\t\t\t\t\treturn strip\n'
    '\t\t\t\tfont_size = max(10, LABEL_H - 6)\n'
    '\t\t\t\ttry:\n'
    '\t\t\t\t\tfnt = ImageFont.truetype(\'arial.ttf\', font_size)\n'
    '\t\t\t\texcept Exception:\n'
    '\t\t\t\t\tfnt = ImageFont.load_default()\n'
    '\t\t\t\ttmp = Image.new(\'RGB\', (1, 1))\n'
    '\t\t\t\tbbox = ImageDraw.Draw(tmp).textbbox((0, 0), text, font=fnt)\n'
    '\t\t\t\ttw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]\n'
    '\t\t\t\ttx, ty = 3, (LABEL_H - th) // 2\n'
    '\t\t\t\tmask_img = Image.new(\'L\', (w, LABEL_H), 0)\n'
    '\t\t\t\tImageDraw.Draw(mask_img).text((tx, ty), text, font=fnt, fill=255)\n'
    '\t\t\t\tmask_np = np.asarray(mask_img, dtype=np.float32) / 255.0\n'
    '\t\t\t\tyy, xx = np.meshgrid(np.arange(LABEL_H), np.arange(w), indexing=\'ij\')\n'
    '\t\t\t\td = ((xx - tx) + (yy - ty)).astype(np.float32) / max(1, tw + th)\n'
    '\t\t\t\td = np.clip(d, 0, 1)\n'
    '\t\t\t\tt = (iter_val or 0) * 2.0\n'
    '\t\t\t\thue = 0.62 + d * 0.23 + np.sin(t + d * np.pi * 2) * 0.04\n'
    '\t\t\t\tsat = 0.85 + np.sin(t * 0.7 + d) * 0.15\n'
    '\t\t\t\tval = 0.75 + np.sin(t * 0.5 + d * 1.5) * 0.25\n'
    '\t\t\t\thsv_h = hue % 1.0\n'
    '\t\t\t\thi = (hsv_h * 6).astype(np.int32) % 6\n'
    '\t\t\t\tf = hsv_h * 6 - np.floor(hsv_h * 6)\n'
    '\t\t\t\tp = val * (1.0 - sat)\n'
    '\t\t\t\tq = val * (1.0 - f * sat)\n'
    '\t\t\t\tt_ = val * (1.0 - (1.0 - f) * sat)\n'
    '\t\t\t\tr = np.select([hi == 0, hi == 1, hi == 2, hi == 3, hi == 4, hi == 5],\n'
    '\t\t\t\t              [val, q, p, p, t_, val])\n'
    '\t\t\t\tg = np.select([hi == 0, hi == 1, hi == 2, hi == 3, hi == 4, hi == 5],\n'
    '\t\t\t\t              [t_, val, val, q, p, p])\n'
    '\t\t\t\tb = np.select([hi == 0, hi == 1, hi == 2, hi == 3, hi == 4, hi == 5],\n'
    '\t\t\t\t              [p, p, t_, val, val, q])\n'
    '\t\t\t\tfor c_idx, color in enumerate([b, g, r]):\n'
    '\t\t\t\t\tstrip[:, :, c_idx] = np.where(mask_np > 0, color, strip[:, :, c_idx])\n'
    '\t\t\t\treturn strip\n'
    '\n'
    '\t\t\titer_val = self.iter\n'
    '\t\t\tfor i in range(n_samples):\n'
    '\t\t\t\ts_txt = Path(src_fnames[i]).stem if i < len(src_fnames) and src_fnames[i] else \'\'\n'
    '\t\t\t\td_txt = Path(dst_fnames[i]).stem if i < len(dst_fnames) and dst_fnames[i] else \'\'\n'
    '\t\t\t\tw = S[i].shape[1]\n'
    '\t\t\t\ts_strip = _label_strip(w, s_txt, iter_val)\n'
    '\t\t\t\td_strip = _label_strip(w, d_txt, iter_val)\n'
    '\t\t\t\tlbl = f"{s_txt[:6]}\\u2192{d_txt[:6]}" if s_txt and d_txt else \'SWAP\'\n'
    '\t\t\t\tsw_strip = _label_strip(w, lbl, iter_val)\n'
    '\t\t\t\tempty_strip = _label_strip(w, \'\', iter_val)\n'
    '\t\t\t\tS[i] = np.concatenate([S[i], s_strip], axis=0)\n'
    '\t\t\t\tSS[i] = np.concatenate([SS[i], s_strip], axis=0)\n'
    '\t\t\t\tD[i] = np.concatenate([D[i], d_strip], axis=0)\n'
    '\t\t\t\tDD[i] = np.concatenate([DD[i], d_strip], axis=0)\n'
    '\t\t\t\tSD_025[i] = np.concatenate([SD_025[i], sw_strip], axis=0)\n'
    '\t\t\t\tSD_050[i] = np.concatenate([SD_050[i], sw_strip], axis=0)\n'
    '\t\t\t\tSD_065[i] = np.concatenate([SD_065[i], sw_strip], axis=0)\n'
    '\t\t\t\tSD_075[i] = np.concatenate([SD_075[i], sw_strip], axis=0)\n'
    '\t\t\t\tSD_100[i] = np.concatenate([SD_100[i], sw_strip], axis=0)\n'
    '\t\t\t\tWS[i] = np.concatenate([WS[i], empty_strip], axis=0)\n'
    '\t\t\t\tWD[i] = np.concatenate([WD[i], empty_strip], axis=0)\n'
    '\n'
    '\t\t\tLABEL_H = 22\n'
    '\t\t\tpad_hw = ((0, 0), (0, LABEL_H), (0, 0), (0, 0))\n'
    '\t\t\tDDM_000 = np.pad(DDM_000, pad_hw, constant_values=1.0)\n'
    '\t\t\tDDM_025 = np.pad(DDM_025, pad_hw, constant_values=1.0)\n'
    '\t\t\tSDM_025 = np.pad(SDM_025, pad_hw, constant_values=1.0)\n'
    '\t\t\tDDM_050 = np.pad(DDM_050, pad_hw, constant_values=1.0)\n'
    '\t\t\tSDM_050 = np.pad(SDM_050, pad_hw, constant_values=1.0)\n'
    '\t\t\tDDM_065 = np.pad(DDM_065, pad_hw, constant_values=1.0)\n'
    '\t\t\tSDM_065 = np.pad(SDM_065, pad_hw, constant_values=1.0)\n'
    '\t\t\tDDM_075 = np.pad(DDM_075, pad_hw, constant_values=1.0)\n'
    '\t\t\tSDM_075 = np.pad(SDM_075, pad_hw, constant_values=1.0)\n'
    '\t\t\tDDM_100 = np.pad(DDM_100, pad_hw, constant_values=1.0)\n'
    '\t\t\tSDM_100 = np.pad(SDM_100, pad_hw, constant_values=1.0)\n'
    '\t\t\ttarget_srcm = np.pad(target_srcm, pad_hw, constant_values=1.0)\n'
    '\t\t\ttarget_dstm = np.pad(target_dstm, pad_hw, constant_values=1.0)\n'
    '\t\t\t_ddm_1ch = np.pad(_ddm_1ch, pad_hw, constant_values=1.0)\n'
    '\t\t\t_sdm_1ch = np.pad(_sdm_1ch, pad_hw, constant_values=1.0)\n'
    '\t\t\t_ddm_100_1ch = np.pad(_ddm_100_1ch, pad_hw, constant_values=1.0)\n'
    '\t\t\t_sdm_100_1ch = np.pad(_sdm_100_1ch, pad_hw, constant_values=1.0)\n'
    '\t\texcept Exception:\n'
    '\t\t\tpass\n'
)

new = (
    '\t\t# ---- filename labels below each cell (purple-blue gradient strip) ----\n'
    '\t\ttry:\n'
    '\t\t\tsrc_fnames = self.last_filenames[0] if hasattr(self, \'last_filenames\') and len(self.last_filenames) > 0 else []\n'
    '\t\t\tdst_fnames = self.last_filenames[1] if hasattr(self, \'last_filenames\') and len(self.last_filenames) > 1 else []\n'
    '\n'
    '\t\t\tdef _label_strip(w, text, iter_val):\n'
    '\t\t\t\tLABEL_H = 24\n'
    '\t\t\t\tstrip = np.full((LABEL_H, w, 3), 0.04, dtype=np.float32)\n'
    '\t\t\t\tif not text:\n'
    '\t\t\t\t\treturn strip\n'
    '\t\t\t\timport cv2\n'
    '\t\t\t\tfscale = 0.5\n'
    '\t\t\t\tthick = 1\n'
    '\t\t\t\tfont = cv2.FONT_HERSHEY_SIMPLEX\n'
    '\t\t\t\t(tw, th), _ = cv2.getTextSize(text, font, fscale, thick)\n'
    '\t\t\t\ttx, ty = 4, LABEL_H - 5\n'
    '\t\t\t\tmask_u8 = np.zeros((LABEL_H, w), dtype=np.uint8)\n'
    '\t\t\t\tcv2.putText(mask_u8, text, (tx, ty), font, fscale, 255, thick, cv2.LINE_AA)\n'
    '\t\t\t\tmask_np = mask_u8.astype(np.float32) / 255.0\n'
    '\t\t\t\tyy, xx = np.meshgrid(np.arange(LABEL_H), np.arange(w), indexing=\'ij\')\n'
    '\t\t\t\td = ((xx - tx) + (yy - ty)).astype(np.float32) / max(1, tw + th)\n'
    '\t\t\t\td = np.clip(d, 0, 1)\n'
    '\t\t\t\tt = (iter_val or 0) * 2.0\n'
    '\t\t\t\thue = 0.62 + d * 0.23 + np.sin(t + d * np.pi * 2) * 0.04\n'
    '\t\t\t\tsat = 0.85 + np.sin(t * 0.7 + d) * 0.15\n'
    '\t\t\t\tval = 0.75 + np.sin(t * 0.5 + d * 1.5) * 0.25\n'
    '\t\t\t\thsv_h = hue % 1.0\n'
    '\t\t\t\thi = (hsv_h * 6).astype(np.int32) % 6\n'
    '\t\t\t\tf = hsv_h * 6 - np.floor(hsv_h * 6)\n'
    '\t\t\t\tp = val * (1.0 - sat)\n'
    '\t\t\t\tq = val * (1.0 - f * sat)\n'
    '\t\t\t\tt_ = val * (1.0 - (1.0 - f) * sat)\n'
    '\t\t\t\tr = np.select([hi == 0, hi == 1, hi == 2, hi == 3, hi == 4, hi == 5],\n'
    '\t\t\t\t              [val, q, p, p, t_, val])\n'
    '\t\t\t\tg = np.select([hi == 0, hi == 1, hi == 2, hi == 3, hi == 4, hi == 5],\n'
    '\t\t\t\t              [t_, val, val, q, p, p])\n'
    '\t\t\t\tb = np.select([hi == 0, hi == 1, hi == 2, hi == 3, hi == 4, hi == 5],\n'
    '\t\t\t\t              [p, p, t_, val, val, q])\n'
    '\t\t\t\tfor c_idx, color in enumerate([b, g, r]):\n'
    '\t\t\t\t\tstrip[:, :, c_idx] = np.where(mask_np > 0, color, strip[:, :, c_idx])\n'
    '\t\t\t\treturn strip\n'
    '\n'
    '\t\t\titer_val = self.iter\n'
    '\t\t\tfor i in range(n_samples):\n'
    '\t\t\t\ts_txt = Path(src_fnames[i]).stem if i < len(src_fnames) and src_fnames[i] else \'\'\n'
    '\t\t\t\td_txt = Path(dst_fnames[i]).stem if i < len(dst_fnames) and dst_fnames[i] else \'\'\n'
    '\t\t\t\tw = S[i].shape[1]\n'
    '\t\t\t\ts_strip = _label_strip(w, s_txt, iter_val)\n'
    '\t\t\t\td_strip = _label_strip(w, d_txt, iter_val)\n'
    '\t\t\t\tlbl = f"{s_txt[:6]}\\u2192{d_txt[:6]}" if s_txt and d_txt else \'SWAP\'\n'
    '\t\t\t\tsw_strip = _label_strip(w, lbl, iter_val)\n'
    '\t\t\t\tempty_strip = _label_strip(w, \'\', iter_val)\n'
    '\t\t\t\tS[i] = np.concatenate([S[i], s_strip], axis=0)\n'
    '\t\t\t\tSS[i] = np.concatenate([SS[i], s_strip], axis=0)\n'
    '\t\t\t\tD[i] = np.concatenate([D[i], d_strip], axis=0)\n'
    '\t\t\t\tDD[i] = np.concatenate([DD[i], d_strip], axis=0)\n'
    '\t\t\t\tSD_025[i] = np.concatenate([SD_025[i], sw_strip], axis=0)\n'
    '\t\t\t\tSD_050[i] = np.concatenate([SD_050[i], sw_strip], axis=0)\n'
    '\t\t\t\tSD_065[i] = np.concatenate([SD_065[i], sw_strip], axis=0)\n'
    '\t\t\t\tSD_075[i] = np.concatenate([SD_075[i], sw_strip], axis=0)\n'
    '\t\t\t\tSD_100[i] = np.concatenate([SD_100[i], sw_strip], axis=0)\n'
    '\t\t\t\tWS[i] = np.concatenate([WS[i], empty_strip], axis=0)\n'
    '\t\t\t\tWD[i] = np.concatenate([WD[i], empty_strip], axis=0)\n'
    '\n'
    '\t\t\tLABEL_H = 24\n'
    '\t\t\tpad_hw = ((0, 0), (0, LABEL_H), (0, 0), (0, 0))\n'
    '\t\t\tDDM_000 = np.pad(DDM_000, pad_hw, constant_values=1.0)\n'
    '\t\t\tDDM_025 = np.pad(DDM_025, pad_hw, constant_values=1.0)\n'
    '\t\t\tSDM_025 = np.pad(SDM_025, pad_hw, constant_values=1.0)\n'
    '\t\t\tDDM_050 = np.pad(DDM_050, pad_hw, constant_values=1.0)\n'
    '\t\t\tSDM_050 = np.pad(SDM_050, pad_hw, constant_values=1.0)\n'
    '\t\t\tDDM_065 = np.pad(DDM_065, pad_hw, constant_values=1.0)\n'
    '\t\t\tSDM_065 = np.pad(SDM_065, pad_hw, constant_values=1.0)\n'
    '\t\t\tDDM_075 = np.pad(DDM_075, pad_hw, constant_values=1.0)\n'
    '\t\t\tSDM_075 = np.pad(SDM_075, pad_hw, constant_values=1.0)\n'
    '\t\t\tDDM_100 = np.pad(DDM_100, pad_hw, constant_values=1.0)\n'
    '\t\t\tSDM_100 = np.pad(SDM_100, pad_hw, constant_values=1.0)\n'
    '\t\t\ttarget_srcm = np.pad(target_srcm, pad_hw, constant_values=1.0)\n'
    '\t\t\ttarget_dstm = np.pad(target_dstm, pad_hw, constant_values=1.0)\n'
    '\t\t\t_ddm_1ch = np.pad(_ddm_1ch, pad_hw, constant_values=1.0)\n'
    '\t\t\t_sdm_1ch = np.pad(_sdm_1ch, pad_hw, constant_values=1.0)\n'
    '\t\t\t_ddm_100_1ch = np.pad(_ddm_100_1ch, pad_hw, constant_values=1.0)\n'
    '\t\t\t_sdm_100_1ch = np.pad(_sdm_100_1ch, pad_hw, constant_values=1.0)\n'
    '\t\texcept Exception:\n'
    '\t\t\timport traceback; traceback.print_exc()\n'
)

if old in content:
    content = content.replace(old, new, 1)
    with open(f, 'w', encoding='utf-8') as fp:
        fp.write(content)
    print('AMP replacement OK')
else:
    print('AMP old string NOT FOUND')
    # Find it
    idx = content.find('filename labels below each cell')
    if idx >= 0:
        print('Found comment, checking indentation...')
        print(repr(content[idx:idx+50]))
